name: CI

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: update database
        run: |
          composer init -n --name=topvisor/geolite2
          git config --global user.email "artem.artemkin@topvisor.com"
          git config --global user.name "Artyom Artyomkin"
          git commit -m "build package topvisor/geolite2" || exit 1
          git push || exit 1
