name: CI

on:
  schedule:
    - cron: '0 0 1 * *'

  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: update database
        env:
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
        run: |
          git config user.name maxmind-updater
          git config user.email maxmind-updater@github-actions

          echo "Downloading .tar.gz with database."
          curl -o geoLite2City.tar.gz --url "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=$MAXMIND_LICENSE_KEY&suffix=tar.gz" || exit 1

          echo "Untaring database"
          tar -xzvf geoLite2City.tar.gz || exit 1
          ls -la

          echo "Removing archive"
          rm -f geoLite2City.tar.gz
          ls -la

          geoLite2CityDir="$(ls | grep "GeoLite2-City_" | head -n 1)"
          if [ -z "$geoLite2CityDir" ]; then exit 1; fi
          ls -la

          geoliteCityDbDestPath="src/GeoLite2-City.mmdb"
          mv -f "$geoLite2CityDir/GeoLite2-City.mmdb" "$geoliteCityDbDestPath" || exit 1
          rm -rf "./$geoLite2CityDir"
          ls -la

          git add "$geoliteCityDbDestPath" || exit 1
          if ! git diff-index --quiet HEAD; then
            git commit -m "update GeoLite2-City.mmdb" || exit 1
            git push || exit 1
          fi

